### ISSUE TITLE
Inclusion of this Packages Versions On Pulsar

### ISSUE THREAD

**Issue by confused-Techie** [kraih/atom-perltidy#13]
Hello! I'm a core developer on the Atom fork [Pulsar](https://github.com/pulsar-edit), and my major role has been creating a new Backend for the Pulsar Editor so that once Atom's is shut down we are still able to install and publish packages.

During this process I have archived every single package that was originally published to Atom, and have been migrating them to our new backend. Your package included. (But if you'd like for your package to be removed that is totally fine feel free to let me know).

But unfortunately some of your packages versions are not compatible with this new backend.

Specifically we enforce the use of Semver V2 `versions` in the `package.json` and previously not every single version of your package did this.

Specifically:

* `0.1`
* `0.2`
* `0.3`

But I'd hate to have to exclude these versions of your package if I didn't have to, so if you'd like just let me know what Valid Semver V2 format these would be okay to change as and we are good to go. 

So really you don't need to do anything other than say to change to `0.0.1` or `0.1.0` or `0.0.1-beta` or whatever, or advise if you'd like your package to removed as a whole from the new Pulsar Backend.

Otherwise non-response means I'll go ahead and automatically remove these versions from the backend while leaving all other compatible versions up.

Thanks so much for your time and hope you have a great day!

**Comment by clarking** [comment]
Hi @confused-Techie 
It seems that this package is unmaintained. As a former user that wants to try it on Pulsar and since the versions that you mention are too far away and giving that 4.x is was the last active branch, i think it's safe to remove them.  

Thank you!

**Comment by confused-Techie** [comment]
> Hi @confused-Techie It seems that this package is unmaintained. As a former user that wants to try it on Pulsar and since the versions that you mention are too far away and giving that 4.x is was the last active branch, i think it's safe to remove them.
> 
> Thank you!

Thanks so much for giving some pointers here. But it does look like the author may not respond. I'll allow them some time to do so, but otherwise you'll be glad to know that 4.x should be totally good to go, and happy to hear you'll be there to make sure it works.

**Comment by confused-Techie** [comment]
Based on @clarking suggestions, I've just gone ahead and deleted the offending versions.

Thanks a ton for your time, have a great day!
